# Generated by Django 4.2.3 on 2023-07-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopart',
            name='start_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videopart',
            name='stop_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
